pkg/openapi/cluster/usecase/global_config_usecase.go, pkg/openapi/model/cluster.go
=> custom http domain

ui/.browserslistrc, ui/.editorconfig, ui/.env, ui/.env.development, ui/.env.github, ui/.env.netlify, ui/.env.preview, ui/.eslintignore, ui/.eslintrc.js, ui/.gitignore, ui/.postcssrc.js, ui/dependencies-cdn.js, ui/src/api/installProcess.js, ui/src/layout/header-aside/components/menu-side/index.js, ui/src/layout/header-aside/layout.vue, ui/src/menu/aside.js, ui/src/views/InstallProcess/components/clusterConfiguration/index.vue, ui/src/views/InstallProcess/components/installResults/index.vue, ui/src/views/InstallProcess/components/installResults/installComponent.vue, ui/src/views/InstallProcess/components/installResults/rainbondComponent.vue, ui/src/views/InstallProcess/components/successfulInstallation/index.vue, ui/src/views/InstallProcess/components/upload/index.vue, ui/src/views/InstallProcess/index.vue, ui/src/views/system/index/components/d2-help/index.vue
=> [REV] Modify the ui code

ui/src/api/installProcess.js, ui/src/plugin/axios/index.js, ui/src/store/modules/installProcess.js, ui/src/views/InstallProcess/components/clusterConfiguration/index.vue, ui/src/views/InstallProcess/components/installResults/index.vue, ui/src/views/InstallProcess/components/installResults/installComponent.vue, ui/src/views/InstallProcess/components/successfulInstallation/index.vue, ui/src/views/InstallProcess/components/upload/index.vue, ui/src/views/InstallProcess/index.vue, ui/src/views/system/index/components/d2-help/index.vue
=> [REV] Modify the code

pkg/openapi/cluster/usecase/cluster_usecase.go, pkg/openapi/cluster/usecase/component_usecase.go, pkg/openapi/cluster/usecase/global_config_usecase.go, pkg/openapi/cluster/usecase/install_usecase.go
=> skip rainbond storage class

pkg/openapi/cluster/usecase/cluster_usecase.go, pkg/openapi/cluster/usecase/global_config_usecase.go
初始化和修改的时候，设定cluster的InstallMode为WithPackage
=> set installMode as default withpackage

pkg/openapi/cluster/usecase/install_usecase.go
=> install component status wait handle image status

pkg/openapi/cluster/usecase/component_usecase.go
使用pod的condition（PodReady）标识pod是否就绪
notReady是显示message和reason
=> pod status fix

pkg/openapi/cluster/usecase/install_usecase.go
do not create grctl component now
=> remove grctl now

pkg/openapi/cluster/usecase/component_usecase.go
=> fix metrics

pkg/openapi/cluster/usecase/install_usecase.go
不使用cluster配置InstallMode来妨碍package的进度
=> fix package progress error

pkg/openapi/cluster/usecase/install_usecase.go
=> fix codding/620 package info status nil

pkg/openapi/cluster/usecase/component_usecase.go
组件副本数必须大于0并且和就绪副本数相等才认为是Running状态
=> fix coding/611 progress is not corrent

pkg/controller/rbdcomponent/handler/chaos.go, pkg/util/constants/constants.go
=> fix coding 605 bugs

pkg/openapi/cluster/usecase/global_config_usecase.go
使用网关外网IP来解析grapps.cn，默认使用网关节点IP
=> fix coding/646

ui/src/views/InstallProcess/components/installResults/index.vue, ui/src/views/InstallProcess/components/installResults/rainbondComponent.vue, ui/src/views/system/index/components/d2-help/index.vue, ui/src/views/system/index/page.vue
=> fix the style

ui/src/views/InstallProcess/components/installResults/index.vue, ui/src/views/InstallProcess/components/installResults/installComponent.vue, ui/src/views/system/index/components/d2-help/index.vue
=> fix bug 714 746 

pkg/controller/rbdcomponent/handler/eventlog.go
修改eventLog的etcd启动参数，不使用通用的etcd参数
=> modify eventlog etcd args

pkg/openapi/cluster/usecase/global_config_usecase.go
=> fullset of gatewaynode while update cluster

pkg/openapi/cluster/repository.go, pkg/openapi/cluster/repository/cluster.go, pkg/openapi/cluster/usecase/cluster_usecase.go, pkg/openapi/cluster/usecase/component_usecase.go, pkg/openapi/cluster/usecase/global_config_usecase.go, pkg/openapi/cluster/usecase/install_usecase.go, pkg/openapi/cluster/usecase/usecase_impl.go
1、对接前端，任何时候均提供企业id和安装信息
2、修复代码不规范语法
=> update install log and some code format

ui/src/views/InstallProcess/components/clusterConfiguration/index.vue, ui/src/views/system/index/page.vue
=> [REV] Modify the Setup external database cannot start installation

ui/src/views/InstallProcess/components/installResults/rainbondComponent.vue
=> [REV] Modify the Component status and message presentation

pkg/controller/rbdcomponent/handler/app-ui.go
rbd-app-ui component use ui database
=> update ui database set

pkg/openapi/cluster/usecase/component_usecase.go, pkg/openapi/types/v1/cluster.go
添加组件的排序
方案：实现sort接口，根据组件的名称升序排序
=> sort component

ui/public/index.html, ui/vue.config.js
=> [REV] Modify the Cancel the offline

ui/src/views/InstallProcess/components/installResults/index.vue, ui/src/views/InstallProcess/components/successfulInstallation/index.vue, ui/src/views/InstallProcess/index.vue, ui/vue.config.js
=> [ADD]  uninstall 

ui/src/locales/en.json, ui/src/locales/zh-chs.json
"Rainbond V5.2.0-release 集群安装控制器",
=> [REV] Modify the title

ui/src/views/InstallProcess/components/clusterConfiguration/index.vue, ui/src/views/InstallProcess/components/installResults/index.vue, ui/src/views/InstallProcess/components/successfulInstallation/index.vue, ui/src/views/InstallProcess/index.vue, ui/src/views/system/index/components/d2-help/index.vue
=> [REV] Modify the The ginseng problem

ui/src/plugin/d2admin/index.js, ui/src/views/InstallProcess/components/installResults/index.vue, ui/src/views/InstallProcess/components/successfulInstallation/index.vue, ui/src/views/InstallProcess/index.vue, ui/src/views/system/index/components/d2-help/index.vue
=> [REV] Modify the Uninstall reason

pkg/controller/rbdcomponent/handler/api.go, pkg/controller/rbdcomponent/handler/app-ui.go, pkg/controller/rbdcomponent/handler/chaos.go, pkg/controller/rbdcomponent/handler/eventlog.go, pkg/controller/rbdcomponent/handler/gateway.go, pkg/controller/rbdcomponent/handler/monitor.go, pkg/controller/rbdcomponent/handler/node.go, pkg/controller/rbdcomponent/handler/worker.go, pkg/util/probeutil/probeutil.go, pkg/util/probeutil/probeutil_test.go
=> add liveness and readiness probe

ui/src/api/installProcess.js, ui/src/store/modules/installProcess.js, ui/src/views/InstallProcess/components/clusterConfiguration/index.vue, ui/src/views/InstallProcess/components/installResults/installComponent.vue
=> [REV] Modify the Add gateway problem troubleshooting

ui/src/views/InstallProcess/components/clusterConfiguration/index.vue
=> Modify the  Gateway extranet IP when installed

ui/src/api/installProcess.js, ui/src/locales/zh-chs.json, ui/src/router/routes.js, ui/src/store/modules/installProcess.js, ui/src/views/InstallProcess/components/clusterConfiguration/index.vue, ui/src/views/InstallProcess/components/detection/index.vue, ui/src/views/InstallProcess/components/successfulInstallation/index.vue, ui/src/views/InstallProcess/index.vue, ui/src/views/system/index/components/d2-help/index.vue, ui/src/views/system/index/page.vue
=> ADD the  Configuration testing page

ui/src/views/InstallProcess/index.vue
=> Modify the  component

ui/src/views/InstallProcess/components/installResults/installComponent.vue
=> Modify the  style

ui/src/views/InstallProcess/components/clusterConfiguration/index.vue, ui/src/views/InstallProcess/components/detection/index.vue
=> Modify the  text

ui/src/api/installProcess.js, ui/src/locales/zh-chs.json, ui/src/plugin/axios/index.js, ui/src/store/modules/installProcess.js, ui/src/views/InstallProcess/components/successfulInstallation/index.vue
=> Modify the  upgrade version

ui/src/views/InstallProcess/components/detection/index.vue, ui/src/views/system/index/page.vue
=> Modify the  step

ui/src/views/InstallProcess/components/detection/index.vue, ui/src/views/system/index/page.vue
=> Modify the  version

ui/src/views/InstallProcess/components/successfulInstallation/index.vue
=> Modify the  Install the completed page and collect the console address

ui/src/views/InstallProcess/components/successfulInstallation/index.vue, ui/src/views/system/index/page.vue
=> Modify the  ginseng

ui/src/views/InstallProcess/components/successfulInstallation/index.vue
=> Modify the install describe

ui/src/plugin/axios/index.js
=> Modify the To prevent an error

.gitignore, controllers/handler/api.go, controllers/handler/app-ui.go, controllers/handler/hub.go, util/k8sutil/k8sutil.go
Upgrade Ingress from extensions/v1beta1 to networking.k8s.io/v1
=> Feature: upgrade ingress to networking v1

controllers/rainbondpackage_controller.go
refer to: https://github.com/goodrain/rainbond/pull/1107
=> Fix Bug: Pull the mesh and probe plugin in advance

chart/templates/crd/rainbond.io_componentdefinitions.yaml, chart/templates/crd/rainbond.io_helmapps.yaml, chart/templates/crd/rainbond.io_thirdcomponents.yaml, controllers/rainbondpackage_controller.go
refer to: https://github.com/goodrain/rainbond/pull/1108
=> Fix Bug: modified crd yaml

config/single_node_cr/dashboard-metrics-scraper.yml, config/single_node_cr/kubernetes-dashboard.yml, config/single_node_cr/metrics-server.yml, config/single_node_cr/rbd-api.yml, config/single_node_cr/rbd-chaos.yml, config/single_node_cr/rbd-db.yml, config/single_node_cr/rbd-etcd.yml, config/single_node_cr/rbd-eventlog.yml, config/single_node_cr/rbd-gateway.yml, config/single_node_cr/rbd-hub.yml, config/single_node_cr/rbd-monitor.yml, config/single_node_cr/rbd-mq.yml, config/single_node_cr/rbd-node.yml, config/single_node_cr/rbd-resource-proxy.yml, config/single_node_cr/rbd-webcli.yml, config/single_node_cr/rbd-worker.yml, config/single_node_cr/rbdcluster.yml, config/single_node_cr/rbdpackage.yml, config/single_node_cr/rbdvolume.yml, controllers/handler/api.go, controllers/handler/chaos.go, controllers/handler/common.go, controllers/handler/eventlog.go, controllers/handler/hub.go, controllers/handler/node.go, controllers/handler/uitls.go, controllers/handler/worker.go, controllers/plugin/nfs/nfs.go, controllers/rainbondcluster_controller.go, util/suffixdomain/suffixdomain.go
=> New Feature: Supports stand-alone node installation using local storage

.drone.yml, config/single_node_cr/dashboard-metrics-scraper.yml, config/single_node_cr/kubernetes-dashboard.yml, config/single_node_cr/metrics-server.yml, config/single_node_cr/rbd-api.yml, config/single_node_cr/rbd-chaos.yml, config/single_node_cr/rbd-db.yml, config/single_node_cr/rbd-etcd.yml, config/single_node_cr/rbd-eventlog.yml, config/single_node_cr/rbd-gateway.yml, config/single_node_cr/rbd-hub.yml, config/single_node_cr/rbd-monitor.yml, config/single_node_cr/rbd-mq.yml, config/single_node_cr/rbd-node.yml, config/single_node_cr/rbd-resource-proxy.yml, config/single_node_cr/rbd-webcli.yml, config/single_node_cr/rbd-worker.yml
Signed-off-by: Qi Zhang <smallqi1@163.com>
=> fix: modify dind images

config/single_node_cr/rbd-chaos.yml, config/single_node_cr/rbd-node.yml
Signed-off-by: Qi Zhang <smallqi1@163.com>
=> fix: modify container sock path

config/single_node_cr/rbd-chaos.yml
Signed-off-by: Qi Zhang <smallqi1@163.com>
=> fix: modify containerd mount path

controllers/handler/api.go
Create rbd-api-healthz service and ingress automatically. So that the rbd-api health check endpoint will worked in rbd-gateway.
=> feat: create rbd-api-healthz svc and ingress automatically

controllers/handler/hub.go
=> feat: add tls key field

controllers/handler/eventlog.go, controllers/handler/mq.go, controllers/handler/node.go, controllers/handler/webcli.go, controllers/handler/worker.go
=> feat: add rbd service

controllers/handler/mq.go, controllers/handler/webcli.go
=> fix: service name

controllers/handler/api.go, controllers/handler/apigateway.go, controllers/handler/app-ui.go, controllers/handler/hub.go, go.mod
=> fix: api-gateway routes

controllers/add_handler.go, controllers/handler/app-ui.go, controllers/handler/common.go
=> fix: api gateway 

config/prom/prometheus.yml, config/prom/rules.yml, controllers/handler/chaos.go, controllers/handler/monitor.go, controllers/handler/mq.go, controllers/handler/worker.go
=> feat: add rbd-monitor

controllers/cluster-mgr/precheck/container_network.go, controllers/handler/api.go, controllers/handler/apigateway.go, controllers/handler/app-ui.go, controllers/handler/chaos.go, controllers/handler/common.go, controllers/handler/dashbaordmetricsscraper.go, controllers/handler/eventlog.go, controllers/handler/gateway.go, controllers/handler/hub.go, controllers/handler/k8sdashbaord.go, controllers/handler/metrics_server.go, controllers/handler/monitor.go, controllers/handler/mq.go, controllers/handler/node.go, controllers/handler/webcli.go, controllers/handler/worker.go, controllers/plugin/aliyunclouddisk/aliyunclouddisk.go, controllers/plugin/aliyunnas/aliyunnas.go, controllers/plugin/nfs/nfs.go, controllers/rainbondcluster_controller.go, util/commonutil/file.go, util/k8sutil/k8sutil.go
=> Change rbd system

controllers/cluster-mgr/precheck/container_network.go, controllers/component-mgr/component.go, controllers/handler/api.go, controllers/handler/apigateway.go, controllers/handler/app-ui.go, controllers/handler/chaos.go, controllers/handler/common.go, controllers/handler/dashbaordmetricsscraper.go, controllers/handler/eventlog.go, controllers/handler/gateway.go, controllers/handler/hub.go, controllers/handler/k8sdashbaord.go, controllers/handler/metrics_server.go, controllers/handler/monitor.go, controllers/handler/mq.go, controllers/handler/node.go, controllers/handler/webcli.go, controllers/handler/worker.go, controllers/plugin/aliyunclouddisk/aliyunclouddisk.go, controllers/plugin/aliyunnas/aliyunnas.go, controllers/plugin/nfs/nfs.go, controllers/rainbondcluster_controller.go, util/commonutil/file.go, util/k8sutil/k8sutil.go
=> feat: support change rainbond namespace

controllers/handler/apigateway.go
=> feat: change gateway image
